name: rails

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        ports:
          - 5432:5432

        env:
          POSTGRES_DB: ddbj_repository_test
          POSTGRES_HOST_AUTH_METHOD: trust

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: api

    env:
      BUNDLE_WITHOUT: development
      PGHOST: localhost
      PGUSER: postgres
      RAILS_ENV: test
      TZ: Japan

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: schema

      - run: bundle exec thor schema:generate_copy
        working-directory: schema

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: api

      - run: bundle exec submission-excel2xml download_xsd

      - run: bin/rails db:prepare
      - run: bundle exec rspec
